Traceback (most recent call last):
  File "rnn.py", line 132, in <module>
    r.construct([128], tf.contrib.rnn.LSTMCell)
  File "rnn.py", line 44, in construct
    rnn_outputs, rnn_states = tf.nn.dynamic_rnn(multi_layer_cell, rnn_inputs, dtype = tf.int32, sequence_length = self.seq_lens, swap_memory = True)
  File "/software/anaconda/4.4.0/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 574, in dynamic_rnn
    dtype=dtype)
  File "/software/anaconda/4.4.0/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 737, in _dynamic_rnn_loop
    swap_memory=swap_memory)
  File "/software/anaconda/4.4.0/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2770, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/software/anaconda/4.4.0/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2599, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/software/anaconda/4.4.0/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2549, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/software/anaconda/4.4.0/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 720, in _time_step
    skip_conditionals=True)
  File "/software/anaconda/4.4.0/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 206, in _rnn_step
    new_output, new_state = call_cell()
  File "/software/anaconda/4.4.0/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 708, in <lambda>
    call_cell = lambda: cell(input_t, state)
  File "/software/anaconda/4.4.0/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 180, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/software/anaconda/4.4.0/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 441, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/software/anaconda/4.4.0/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 916, in call
    cur_inp, new_state = cell(cur_inp, cur_state)
  File "/software/anaconda/4.4.0/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 180, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/software/anaconda/4.4.0/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 441, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/software/anaconda/4.4.0/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 542, in call
    lstm_matrix = _linear([inputs, m_prev], 4 * self._num_units, bias=True)
  File "/software/anaconda/4.4.0/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 1021, in _linear
    res = math_ops.matmul(array_ops.concat(args, 1), weights)
  File "/software/anaconda/4.4.0/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1048, in concat
    name=name)
  File "/software/anaconda/4.4.0/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 495, in _concat_v2
    name=name)
  File "/software/anaconda/4.4.0/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 463, in apply_op
    raise TypeError("%s that don't all match." % prefix)
TypeError: Tensors in list passed to 'values' of 'ConcatV2' Op have types [float64, int32] that don't all match.
